#spring.application.name=ecom-application

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true #enable logging of sql in console

#for test purpose for prod use update #automaticalyy create database table based on your entity classes
#spring.jpa.hibernate.ddl-auto=create
#management.endpoints.web.exposure.include='*'

spring:
  application:
    name: ecom-application
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
  server:
    shutdown: graceful


info:
  app:
    name: MyNewApp
    description: App built by us
    version: 1.0.0
